- hosts: webservers

  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
  
    - name: remove git config
      ansible.builtin.file:
        path: /home/{{ item }}/.gitconfig
        state: absent
      loop: "{{ users}}"
      become: yes 
