- hosts: webservers

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: ansible_distribution == "Ubuntu"
      become: yes

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: present
      when: ansible_distribution == "Ubuntu"
      become: yes

    - name: cowsay hello
      ansible.builtin.shell: cowsay "Hello, from web server!"
      register: cowsay_result
      when: ansible_distribution == "Ubuntu"

    - name: update index
      ansible.builtin.template:
        src: ../templates/index.html
        dest: "{{ root_dir }}/index.html"
      when: ansible_distribution == "Ubuntu"
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      when: ansible_distribution == "Ubuntu"
      notify: 
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      when: ansible_distribution == "Ubuntu"
      become: yes  
